# Generated by Django 3.2.12 on 2022-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_word_oxford_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=80, verbose_name='transcription'),
        ),
        migrations.AlterField(
            model_name='word',
            name='oxford_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='oxford data'),
        ),
    ]
