# Generated by Django 3.2.12 on 2022-03-07 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20220307_2258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('word', 'user')},
        ),
    ]
