# Generated by Django 3.2.12 on 2022-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scoreboard_user_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userword',
            name='words_userword_status_valid',
        ),
        migrations.AddConstraint(
            model_name='userword',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['learning', 'learned'])), name='core_userword_status_valid'),
        ),
    ]
