# Generated by Django 3.2.12 on 2022-03-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_userword_constraint'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='score',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scoreboard',
            table=None,
        ),
        migrations.AlterModelTable(
            name='topic',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userword',
            table=None,
        ),
        migrations.AlterModelTable(
            name='word',
            table=None,
        ),
    ]
