# Generated by Django 3.2.12 on 2022-03-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='oxford_data',
            field=models.JSONField(default=dict),
        ),
    ]
